apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: javawebapp
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app
  source:
    path: javawebapp
    repoURL: 'https://github.com/coopengrs15/ArgoCD.git'
    targetRevision: HEAD
   
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true
