apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: javawebapp
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  source:
    path: javawebapp
    repoURL: 'https://github.com/coopengrs15/ArgoCD'
    targetRevision: dev
